namespace DebtCollectionMVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class InsertAreaBandung : DbMigration
    {
        public override void Up()
        {
            Sql("SET IDENTITY_INSERT [dbo].[Areas] ON");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (1, '40611', 'Cigending', 'Ujung Berung', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (2, '40617', 'Pasanggrahan', 'Ujung Berung', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (3, '40619', 'Pasir Endah', 'Ujung Berung', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (4, '40616', 'Pasirjati', 'Ujung Berung', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (5, '40618', 'Pasirwangi', 'Ujung Berung', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (6, '40117', 'Babakan Ciamis', 'Sumur Bandung', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (7, '40111', 'Braga', 'Sumur Bandung', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (8, '40112', 'Kebon Pisang', 'Sumur Bandung', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (9, '40113', 'Merdeka', 'Sumur Bandung', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (10, '40153', 'Geger Kalong', 'Sukasari', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (11, '40154', 'Isola', 'Sukasari', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (12, '40151', 'Sarijadi', 'Sukasari', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (13, '40152', 'Sukarasa', 'Sukasari', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (14, '40162', 'Cipedes', 'Sukajadi', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (15, '40161', 'Pasteur', 'Sukajadi', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (16, '40162', 'Sukabungah', 'Sukajadi', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (17, '40163', 'Sukagalih', 'Sukajadi', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (18, '40164', 'Sukawarna', 'Sukajadi', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (19, '40254', 'Ancol', 'Regol', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (20, '40251', 'Balong Gede', 'Regol', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (21, '40252', 'Ciateul', 'Regol', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (22, '40253', 'Cigereleng', 'Regol', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (23, '40255', 'Ciseureuh', 'Regol', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (24, '40254', 'Pasirluyu', 'Regol', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (25, '40252', 'Pungkur', 'Regol', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (26, '40292', 'Cipamokolan', 'Rancasari', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (27, '40292', 'Darwati', 'Rancasari', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (28, '40295', 'Manjahlega (Cisarantenkidul)', 'Rancasari', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (29, '40292', 'Mekar Mulya (Mekarjaya)', 'Rancasari', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (30, '40614', 'Cipadung Kidul', 'Panyileukan', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (31, '40614', 'Cipadung Kulon', 'Panyileukan', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (32, '40614', 'Cipadung Wetan', 'Panyileukan', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (33, '40614', 'Mekarmulya', 'Panyileukan', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (34, '40195', 'Jatihandap', 'Mandalajati', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (35, '40195', 'Karang Pamulang', 'Mandalajati', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (36, '40195', 'Pasir Impun', 'Mandalajati', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (37, '40195', 'Sindang Jaya', 'Mandalajati', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (38, '40262', 'Burangrang', 'Lengkong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (39, '40265', 'Cijagra', 'Lengkong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (40, '40261', 'Cikawao', 'Lengkong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (41, '40263', 'Lingkar Selatan', 'Lengkong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (42, '40262', 'Malabar', 'Lengkong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (43, '40261', 'Paledang', 'Lengkong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (44, '40264', 'Turangga', 'Lengkong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (45, '40283', 'Babakan Sari', 'Kiaracondong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (46, '40281', 'Babakan Surabaya', 'Kiaracondong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (47, '40282', 'Cicaheum', 'Kiaracondong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (48, '40284', 'Kebon Kangkung', 'Kiaracondong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (49, '40281', 'Kebun Jayanti', 'Kiaracondong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (50, '40285', 'Sukapura', 'Kiaracondong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (51, '40294', 'Cimenerang (Cimincrang)', 'Gedebage', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (52, '40294', 'Cisaranten Kidul', 'Gedebage', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (53, '40294', 'Rancabalong', 'Gedebage', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (54, '40294', 'Rancanumpang', 'Gedebage', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (55, '40131', 'Cipaganti', 'Coblong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (56, '40135', 'Dago', 'Coblong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (57, '40132', 'Lebak Gede', 'Coblong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (58, '40132', 'Lebak Siliwangi', 'Coblong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (59, '40133', 'Sadang Serang', 'Coblong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (60, '40134', 'Sekeloa', 'Coblong', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (61, '40294', 'Babakan Penghulu', 'Cinambo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (62, '40294', 'Cisaranten Wetan', 'Cinambo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (63, '40294', 'Pakemitan', 'Cinambo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (64, '40294', 'Sukamulya', 'Cinambo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (65, '40142', 'Ciumbuleuit', 'Cidadap', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (66, '40141', 'Hegarmanah', 'Cidadap', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (67, '40143', 'Ledeng', 'Cidadap', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (68, '40172', 'Arjuna', 'Cicendo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (69, '40174', 'Husen Sastranegara', 'Cicendo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (70, '40173', 'Pajajaran', 'Cicendo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (71, '40173', 'Pamoyanan', 'Cicendo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (72, '40171', 'Pasir Kaliki', 'Cicendo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (73, '40175', 'Sukaraja', 'Cicendo', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (74, '40614', 'Cipadung', 'Cibiru', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (75, '40614', 'Cisurupan', 'Cibiru', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (76, '40615', 'Palasari', 'Cibiru', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (77, '40615', 'Pasirbiru', 'Cibiru', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (78, '40121', 'Cicadas', 'Cibeunying Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (79, '40124', 'Cikutra', 'Cibeunying Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (80, '40125', 'Padasuka', 'Cibeunying Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (81, '40192', 'Pasirlayung', 'Cibeunying Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (82, '40121', 'Sukamaju', 'Cibeunying Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (83, '40125', 'Sukapada', 'Cibeunying Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (84, '40191', 'Cigadung', 'Cibeunying Kaler', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (85, '40122', 'Cihaur Geulis', 'Cibeunying Kaler', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (86, '40124', 'Neglasari', 'Cibeunying Kaler', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (87, '40123', 'Sukaluyu', 'Cibeunying Kaler', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (88, '40287', 'Cijaura (Margasenang)', 'Buahbatu (Margacinta)', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (89, '40286', 'Jatisari', 'Buahbatu (Margacinta)', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (90, '40286', 'Margasari', 'Buahbatu (Margacinta)', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (91, '40286', 'Sekejati', 'Buahbatu (Margacinta)', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (92, '40236', 'Cibaduyut', 'Bojongloa Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (93, '40239', 'Cibaduyut Kidul', 'Bojongloa Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (94, '40238', 'Cibaduyut Wetan', 'Bojongloa Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (95, '40235', 'Kebon Lega', 'Bojongloa Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (96, '40237', 'Mekarwangi', 'Bojongloa Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (97, '40234', 'Situsaeur', 'Bojongloa Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (98, '40232', 'Babakan Asih', 'Bojongloa Kaler', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (99, '40232', 'Babakan Tarogong', 'Bojongloa Kaler', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (100, '40231', 'Jamika', 'Bojongloa Kaler', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (101, '40233', 'Kopo', 'Bojongloa Kaler', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (102, '40231', 'Suka Asih', 'Bojongloa Kaler', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (103, '40275', 'Binong', 'Batununggal', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (104, '40273', 'Cibangkong', 'Batununggal', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (105, '40275', 'Gumuruh', 'Batununggal', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (106, '40271', 'Kacapiring', 'Batununggal', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (107, '40274', 'Kebon Gedang', 'Batununggal', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (108, '40272', 'Kebonwaru', 'Batununggal', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (109, '40274', 'Maleer', 'Batununggal', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (110, '40273', 'Samoja', 'Batununggal', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (111, '40114', 'Cihapit', 'Bandung Wetan', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (112, '40115', 'Citarum', 'Bandung Wetan', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (113, '40116', 'Tamansari', 'Bandung Wetan', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (114, '40212', 'Caringin', 'Bandung Kulon', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (115, '40212', 'Cibuntu', 'Bandung Kulon', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (116, '40214', 'Cigondewah Kaler', 'Bandung Kulon', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (117, '40214', 'Cigondewah Kidul', 'Bandung Kulon', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (118, '40215', 'Cigondewah Rahayu', 'Bandung Kulon', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (119, '40213', 'Cijerah', 'Bandung Kulon', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (120, '40215', 'Gempolsari', 'Bandung Kulon', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (121, '40211', 'Warung Muncang', 'Bandung Kulon', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (122, '40266', 'Batununggal', 'Bandung Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (123, '40287', 'Kujangsari', 'Bandung Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (124, '40267', 'Mengger', 'Bandung Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (125, '40256', 'Wates', 'Bandung Kidul', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (126, '40222', 'Babakan', 'Babakan Ciparay', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (127, '40223', 'Babakan Ciparay', 'Babakan Ciparay', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (128, '40227', 'Cirangrang', 'Babakan Ciparay', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (129, '40224', 'Margahayu Utara', 'Babakan Ciparay', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (130, '40225', 'Margasuka', 'Babakan Ciparay', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (131, '40221', 'Sukahaji', 'Babakan Ciparay', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (132, '40241', 'Cibadak', 'Astana Anyar', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (133, '40241', 'Karanganyar', 'Astana Anyar', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (134, '40243', 'Karasak', 'Astana Anyar', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (135, '40242', 'Nyengseret', 'Astana Anyar', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (136, '40242', 'Panjunan', 'Astana Anyar', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (137, '40243', 'Pelindung Hewan', 'Astana Anyar', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (138, '40293', 'Cisaranten Kulon', 'Arcamanik', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (139, '40294', 'Cisarenten Bina Harapan', 'Arcamanik', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (140, '40293', 'Sindang Jaya', 'Arcamanik', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (141, '40293', 'Sukamiskin', 'Arcamanik', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (142, '40291', 'Antapani Kidul', 'Antapani (Cicadas)', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (143, '40291', 'Antapani Kulon', 'Antapani (Cicadas)', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (144, '40291', 'Antapani Tengah', 'Antapani (Cicadas)', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (145, '40291', 'Antapani Wetan', 'Antapani (Cicadas)', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (146, '40184', 'Campaka', 'Andir', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (147, '40182', 'Ciroyom', 'Andir', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (148, '40183', 'Dungus Cariang', 'Andir', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (149, '40184', 'Garuda', 'Andir', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (150, '40181', 'Kebon Jeruk', 'Andir', 'Kota Bandung', 'Jawa Barat')");
            Sql("INSERT INTO [dbo].[Areas] ([Id], [PostalCode], [Village], [SubDistrict], [City], [Province]) VALUES (151, '40184', 'Maleber (Maleer)', 'Andir', 'Kota Bandung', 'Jawa Barat')");
            Sql("SET IDENTITY_INSERT [dbo].[Areas] OFF");
        }
        
        public override void Down()
        {
        }
    }
}
